name: CI - Selenium Java with Chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest  # Menggunakan Windows

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'  # Ganti dengan versi Java kamu

      # 3. Install Chrome
      - name: Install Chrome
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile "chrome_installer.exe"
          Start-Process "chrome_installer.exe" -ArgumentList "/silent" -Wait

      # 4. Download ChromeDriver
      - name: Download ChromeDriver
        run: |
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip" -OutFile "chromedriver.zip"
          Expand-Archive -Path "chromedriver.zip" -DestinationPath "chromedriver"
          $env:PATH += ";$(pwd)\chromedriver"

      # 5. Run Maven Tests
      - name: Run tests
        run: mvn clean test

      # 6. Verify cucumber.json exists
      - name: Verify cucumber.json exists
        run: |
          ls -l target/

      # 8. Upload Artifact with GITHUB_TOKEN
      - name: Upload cucumber.json with GITHUB_TOKEN
        run: |
          echo "Uploading cucumber.json artifact"
          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -F "file=@target/cucumber.json"
